### ISSUE TITLE
Change the problem set up

### ISSUE THREAD

**Issue by pletcher** [learn-co-curriculum/nested-hash-iteration-code-along#10]
This code-along repeats the previous README -- can we change it up a bit?

**Comment by aturkewi** [comment]
@pletcher I took a look at these two labs and I see that they use the same data to start with, but it feels like they really do different things. The previous lab just being sort of an intro to adding to hashes and this lab getting into iteration and pry. Let me know if you have a minute to talk and possible clarify what you're thinking would be good for this lab.

**Comment by pletcher** [comment]
Hm, you make a good point -- we can close this :) Thanks!
