### ISSUE TITLE
favorite ice cream flavors symbol discrepancy

### ISSUE THREAD

**Issue by thekayness** [learn-co-curriculum/nested-hash-iteration-code-along#14]
Hi guys, I just wanted to mention that as it comes forked from github, the contacts.rb file and the bin/contacts file both have the favorite ice cream flavor symbol entered as `favorite_icecream_flavors:` while the contacts_spec.rb file has it defined as `favorite_ice_cream_flavors:`

Thanks!
Kathleen

Let me know if this was one of those things we were supposed to figure out on our own...

**Comment by AnnJohn** [comment]
hi @thekayness sorry about that. Definitely was not intentional. We will fix this soon.

**Comment by thekayness** [comment]
No worries! I was happy to have solved the puzzle.
