### ISSUE TITLE
Solution appears to be incorrect

### ISSUE THREAD

**Issue by dvimont** [learn-co-curriculum/nested-hash-iteration-code-along#19]
The solution for the #remove_strawberry method which is proposed in this code-along appears to be incorrect. It removes the flavor "strawberry" from the favorite_ice_cream_flavors attribute belonging to ANY contact in the hash. The stated intention is to only remove "strawberry" from within the "Freddy Mercury" contact entry. While a more selective iteration can certainly be used (since it seems to be the point of the lesson), a more direct solution is:
`contacts["Freddy Mercury"][:favorite_ice_cream_flavors].delete_if{|flavor| flavor == "strawberry"}`

To stick with the more comprehensively iterative solution, we could put in a check to be sure we are only accessing the "Freddy Mercury" contact:
```
  contacts.each do |person, contact_details_hash|
    if person == "Freddy Mercury"
      contact_details_hash.each do |attribute, data|
        if attribute == :favorite_ice_cream_flavors
          data.delete_if {|ice_cream| ice_cream == "strawberry"}
        end
      end
    end
  end
```

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in issue #20. We will add this to our internal work queue. 

We're closing this issue but invite you to follow the progress. We will notify you when it is resolved.

-- Flatiron Curriculum Team

**Comment by drakeltheryuujin** [comment]
Hi @dvimont,

Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
Thank you for your contribution! 💙
