### ISSUE TITLE
KNOWN ISSUES

### ISSUE THREAD

**Issue by curiositypaths** [learn-co-curriculum/nested-hash-iteration-code-along#20]
PROBLEM: Better align the solution with the stated problem. See issue #19.
NOTIFY: @dvimont

**Comment by drakeltheryuujin** [comment]
The student proposes a viable solution, the simplest course of action would be to use their solution and update method 2, however, I believe that using method 1 would be most efficient to avoid needing to use these extra levels of conditionals. The lab would require a bit too much of a rewrite at this time.

The current solution would also remove `strawberry` from Jon Snow's hash, if `strawberry` existed there. This solution is too loose, especially while teaching students `binding.pry`, we're still overlooking the fact that this would delete this value from any `favorite_ice_cream_flavors` hash it exists within.
