### ISSUE TITLE
There's a typo at the end of "Step 1".

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/nested-hash-iteration-code-along#25]
Hello! At the end of "Step 1" in the README, this is what is written:

"You can also run ruby lib/contacts in the terminal - instead of displaying the the test results, this will puts the results of the remove_strawberry method."

The part that says "ruby lib/contacts" should say "ruby bin/contacts". If you run "ruby lib/contacts" in the terminal, you will get this error: "ruby: No such file or directory -- lib/contacts (LoadError)"

I know it's a small issue, but thanks for looking into it.

Sdcrouse

**Comment by Sdcrouse** [comment]
I think I will have to reopen this, but this time, I'll include a screenshot. I don't think I'm in the wrong directory. I see that you wrote "ruby lib/contacts.rb", which works for me as well. However, the README says that you can run "ruby lib/contacts", and THAT'S what's making the error.

Sdcrouse

**Comment by sgharms** [comment]
@Sdcrouse So the issue is the missing `.rb` extension, is that right?

**Comment by Sdcrouse** [comment]
@sgharms Yes, that's pretty much it. Though, as I mentioned in the issue that I reopened, ruby lib/contacts.rb only outputs anything if the file itself includes a contacts hash and a call to #remove_strawberry. If you just run ruby bin/contacts, that's already been taken care of.

**Comment by Sdcrouse** [comment]
By the way, thanks for taking the time to help out with this. I know it's a relatively small issue.
