### ISSUE TITLE
There is a typo at the end of "Step 1" in the README.

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/nested-hash-iteration-code-along#26]
In the README for this lab, the README mentions at the end of Step 1 that "you can also run ruby lib/contacts in the terminal - instead of displaying the the test results, this will reach the binding.pry". 

I ran "ruby lib/contacts" in the terminal just like the instructions said, but I got this error: 
ruby: No such file or directory -- lib/contacts (LoadError)

If I run "ruby lib/contacts.rb" or "ruby bin/contacts", everything works just fine, but "ruby lib/contacts" does not work.

I know that this is a small issue, but the README needs to say "ruby lib/contacts.rb" or "ruby bin/contacts" instead of "ruby lib/contacts.rb". I should also note that if "ruby lib/contacts.rb" is run, the only way that it will reach the binding.pry statement is if the lib/contacts.rb file itself includes a contacts hash and a call to #remove_strawberry. Otherwise, it will output nothing.

Thanks again for looking into this!

Sdcrouse

P.S. Here are a couple of screenshots to add some clarity. This shows the output from running "ruby lib/contacts" and the output from running "ruby lib/contacts.rb" (with the contacts hash and the call to #remove_strawberry inside the file):

![nested hash iteration codealong screenshot](https://user-images.githubusercontent.com/38870640/44687713-c36c9900-aa06-11e8-9677-c1956801857b.gif)

Here is the output from running "ruby lib/contacts.rb" WITHOUT including the contacts hash or the call to #remove_strawberry in the lib/contacts.rb file. This also shows the output of running "ruby bin/contacts":

![nested hash iteration codealong screenshot 2](https://user-images.githubusercontent.com/38870640/44687790-ff9ff980-aa06-11e8-827f-f4c65e1531ef.gif)

**Comment by sgharms** [comment]
@Sdcrouse Take a look at this diff:

https://github.com/learn-co-curriculum/nested-hash-iteration-code-along/pull/27/files

Will that resolve the issue?

**Comment by Sdcrouse** [comment]
Almost. The first change is correct, although I would recommend mentioning that "ruby lib/contacts.rb" will only reach the binding.pry if the lib/contacts.rb file has the contacts hash defined outside of the #remove_strawberry method, and if it includes a call to #remove_strawberry. To be honest, it may just be easier to change "ruby lib/contacts" to "ruby bin/contacts".

As for the second change, that isn't really necessary. That will cause a LoadError since bin/contacts.rb does not exist. The correct file path is bin/contacts. 

Thanks again for your help!

Sdcrouse

**Comment by sgharms** [comment]
OK @Sdcrouse One last time with feeling: I think the diff [link](https://github.com/learn-co-curriculum/nested-hash-iteration-code-along/pull/27/files) is now correct!

**Comment by sgharms** [comment]
All merged. Thanks for your input.
