### ISSUE TITLE
the binding.pry should return "Freddy", not "Jon".

### ISSUE THREAD

**Issue by morganpstanley** [learn-co-curriculum/nested-hash-iteration-code-along#28]
We're told that this:
```
contacts.each do |person, contact_details_hash|
  if person == "Freddy Mercury"
    contact_details_hash.each do |attribute, data|
      binding.pry
    end
  end
end
```

will result in this:
```
> attribute
=> :name
 
> data
=> "Jon"
```

But because the pry is in a conditional statement that is only true of the person == "Freddy Mecury", data should return "Freddy" instead.

**Comment by Dbhmunro** [comment]
I concur, I found this to still be an issue.

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
