### ISSUE TITLE
Incorrect

### ISSUE THREAD

**Issue by jake0988** [learn-co-curriculum/nested-hash-iteration-code-along#30]
I believe this is incorrect. Step two shows a different outcome than the one you should anticipate if you follow the steps. It should return "Freddy," not "Jon."

Step 2. Iterate over the second level
contacts.each do |person, contact_details_hash|
  if person == "Freddy Mercury"
    contact_details_hash.each do |attribute, data|
      binding.pry
    end
  end
end
Again, let's jump into our binding.pry using learn. You should see:

> attribute
=> :name
 
> data
=> "Jon"

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
