### ISSUE TITLE
Step 1, command calls no argument.

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/nested-hash-iteration-code-along#5]
Step 1 asks students to run the 'ruby bin/contacts' to hit the pry in the code. The problem is that neither 'bin/contacts' or its required '../lib/contacts' have argument to pass to #remove_strawberry(contacts). This results in an error:
```
...../nested-hash-iteration-code-along-v-000/lib/contacts.rb:16:in `remove_strawberry': wrong number of arguments (0 for 1) (ArgumentError)
	from bin/contacts:3:in `<main>'
```
This can be corrected by asking students to run 'rspec spec/contacts_spec.rb', or 'learn' as these will run the test suite, which does pass an argument.

**Comment by AnnJohn** [comment]
@MsUzoAgu there's a PR that fixes this issue
